"""Cited mechanistic rationale + scoped generalisation (v5.0, WS-CITE + WS-GEN).

Every recommendation carries a short, literature-cited "why". Crucially the citations are **drawn from the
curated world-model** (the verifier rule provenance, the writer/delivery/locus DOIs) — not generated by a
language model — so they **resolve by construction**. A hallucinated-citation guard rejects any DOI that is
not in the curated, already-verified set (WS-CITE). Numbers in the rationale remain tool-sourced (the prose is
a presentation layer over verified facts; no quantity is invented).

WS-GEN: generalisation toward adjacent genetic-engineering tasks is **grounded-or-refused** — a task is
answered only if it maps to an existing grounded capability; anything else is refused with a scope statement,
never faked.
"""
from __future__ import annotations

from functools import lru_cache

import yaml

from pen_stack._resources import resource


@lru_cache(maxsize=1)
def curated_dois() -> frozenset[str]:
    """The set of DOIs that appear in the CURATED, already-verified world-model (delivery palette, GSH loci,
    writer panel, rule provenance). A citation is 'grounded' iff its DOI is in this set — so a citation can
    only ever point at a source the substrate has actually curated (no hallucinated references)."""
    dois: set[str] = set()
    veh = yaml.safe_load(resource("configs/delivery_vehicles.yaml").read_text(encoding="utf-8"))["vehicles"]
    for v in veh.values():
        dois.update(v.get("dois", []) or [])
    gsh = yaml.safe_load(resource("configs/gsh_validated_heldout.yaml").read_text(encoding="utf-8"))["gsh"]
    for g in gsh:
        if g.get("doi"):
            dois.add(g["doi"])
    import csv
    with open(resource("data/writer_panel.csv"), encoding="utf-8") as f:
        for row in csv.DictReader(f):
            if row.get("doi"):
                dois.add(row["doi"])
    # rule provenance DOIs
    from pen_stack.rules import load_ruleset
    for r in load_ruleset().rules:
        dois.update(r.provenance.get("doi", []) or [])
    return frozenset(dois)


def citations_grounded(dois: list[str]) -> dict:
    """Hallucinated-citation guard: every cited DOI must be in the curated set. Returns the verdict + any
    ungrounded DOIs (which would be a hallucination and are rejected)."""
    curated = curated_dois()
    ungrounded = [d for d in dois if d not in curated]
    return {"all_grounded": not ungrounded, "ungrounded": ungrounded, "n_checked": len(dois)}


def cited_rationale(design: dict) -> dict:
    """A short, literature-cited mechanistic 'why' for a design, with citations DRAWN FROM the curated
    world-model (so they resolve by construction). Numbers are tool-sourced; the prose is presentation only."""
    from pen_stack.graph import build_graph
    from pen_stack.verify import verify
    g = build_graph()
    v = verify(design)
    fam = design.get("writer_family")
    veh = design.get("delivery_vehicle")
    cites: list[dict] = []
    wnode = g.nodes.get(f"writer:{fam}")
    if wnode:
        for d in wnode.props.get("dois", [])[:1]:
            cites.append({"doi": d, "claim": f"{fam} mechanism / characterisation", "source": "world-model writer"})
    vnode = g.nodes.get(f"vehicle:{veh}")
    if vnode:
        for d in vnode.props.get("dois", [])[:1]:
            cites.append({"doi": d, "claim": f"{veh} delivery properties", "source": "world-model vehicle"})
    form = wnode.props.get("output_form") if wnode else None
    verdict = "legal" if v.legal else "illegal"
    rationale = (f"{fam} ({form}-form) installs a {design.get('cargo_bp')} bp cargo via {veh}; the rule-grounded "
                 f"verifier judges this {verdict}"
                 + (f" (violated: {', '.join(x['rule_id'] for x in v.violations)})" if not v.legal else "")
                 + (f"; calibrated confidence {v.confidence}" if v.confidence is not None else
                    "; confidence abstained (unscored)") + ".")
    guard = citations_grounded([c["doi"] for c in cites])
    return {"design": {k: val for k, val in design.items() if not str(k).startswith("_")},
            "rationale": rationale, "citations": cites, "n_citations": len(cites),
            "citations_grounded": guard["all_grounded"], "ungrounded_citations": guard["ungrounded"],
            "no_fabrication": v.no_fabrication and guard["all_grounded"],
            "note": "citations are drawn from the curated world-model (resolve by construction); numbers are "
                    "verifier-sourced; the prose is a presentation layer (no fabricated quantity)."}


# --------------------------------------------------------------------------------------------------
# WS-GEN - scoped generalisation: grounded-or-refused.
# --------------------------------------------------------------------------------------------------
# adjacent genetic-engineering tasks that MAP to an existing grounded capability (answerable);
# anything else is refused with a scope statement.
_GROUNDED_TASKS = {
    "delivery_selection": "maps to the v3.3 delivery rules (cargo-form + capacity + integration)",
    "write_type_legality": "maps to the v3.3 write-type router + verifier",
    "off_target_screen": "maps to the bridge off-target engine (a screen, not a per-site calculator)",
    "writer_variant_critique": "maps to the v4.0 writer-verification branch (score/critique, never invent)",
}


def generalise(task: str, payload: dict | None = None) -> dict:
    """Answer an adjacent genetic-engineering task ONLY if it maps to a grounded capability; otherwise REFUSE
    with a scope statement (Principle 4: grounded-or-refused, never faked)."""
    payload = payload or {}
    if task not in _GROUNDED_TASKS:
        return {"task": task, "grounded": False, "refused": True,
                "scope_statement": f"'{task}' has no grounding in PEN-STACK; refused rather than faked. "
                                   f"Grounded tasks: {sorted(_GROUNDED_TASKS)}.",
                "no_fabrication": True}
    result: dict = {"task": task, "grounded": True, "refused": False,
                    "grounding": _GROUNDED_TASKS[task], "no_fabrication": True}
    if task in ("delivery_selection", "write_type_legality") and payload:
        from pen_stack.verify import verify
        v = verify(payload)
        result["verdict"] = {"legal": v.legal, "confidence": v.confidence,
                             "violations": [x["rule_id"] for x in v.violations]}
    return result
